# Generated by Django 2.1.8 on 2019-05-04 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_review_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentable_name',
            new_name='author_name',
        ),
    ]
