# Generated by Django 2.1.8 on 2019-05-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20190504_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hits',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
