# Generated by Django 2.1.8 on 2019-05-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('real_name', models.CharField(default='홍길동', max_length=20, verbose_name='real_name')),
                ('phone_number', models.CharField(default='010-0000-0000', max_length=20, verbose_name='phone_number')),
                ('age', models.IntegerField(default=0, verbose_name='age')),
                ('address1', models.CharField(choices=[('10', '서울'), ('20', '강원'), ('30', '대전'), ('31', '충남'), ('33', '세종'), ('36', '충북'), ('40', '인천'), ('41', '경기'), ('50', '광주'), ('51', '전남'), ('56', '전북'), ('60', '부산'), ('62', '경남'), ('68', '울산'), ('69', '제주'), ('70', '대구'), ('71', '경북')], default='10', max_length=2, verbose_name='address1')),
                ('is_paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='username')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'custom_user',
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='custom_user_email_55dec9_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='custom_user_usernam_674d82_idx'),
        ),
    ]
